[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/settings"
  to = "/.netlify/functions/settings"
  status = 200
